# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  persistenceImage: 'persistence-image'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Unit tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: 'jezhik-dockerhub'
    
- task: Docker@2
  displayName: 'Persistence build and push'
  inputs:
    repository: jezhik/hedgehog-persistence
    command: buildAndPush
    buildContext: .
    Dockerfile: Hedgehog.Persistence/Dockerfile
    containerRegistry: 'jezhik-dockerhub'
    tags: |
      $(Build.BuildId)
      latest

- task: Docker@2
  displayName: 'RestApi build and push'
  inputs:
    repository: jezhik/hedgehog-restapi
    command: buildAndPush
    buildContext: .
    Dockerfile: Hedgehog.RestApi/Dockerfile
    containerRegistry: 'jezhik-dockerhub'
    tags: |
      $(Build.BuildId)
      latest
    
- task: Docker@2
  displayName: 'UI build and push'
  inputs:
    repository: jezhik/hedgehog-ui
    command: buildAndPush
    buildContext: .
    Dockerfile: Hedgehog.UI/Dockerfile
    containerRegistry: 'jezhik-dockerhub'
    tags: |
      $(Build.BuildId)
      latest
    
- task: Docker@2
  displayName: Logout of Docker Hub
  inputs:
    command: logout
    containerRegistry: 'jezhik-dockerhub'